### ISSUE TITLE
How do I use these files to create my own builder image?

### ISSUE THREAD

**Issue by drnic** [paketo-buildpacks/builder#6]
https://buildpacks.io/docs/using-pack/working-with-builders/

```
$ pack create-builder drnic/cnb:cflinuxfs3 --builder-config cflinuxfs3-order.toml
ERROR  invalid builder config: stack.id is required
```

Where do I get the latest `[[buildpacks]]` and `[stack]` for the `--builder-config` file?

**Comment by zmackie** [comment]
@drnic The stack configuration is injected dynamically in our pipelines (which are not public at the moment) but https://github.com/cloudfoundry/stacks/blob/master/fixtures/builder.toml is a decent example of what you might want to do.

Post your `order.toml` and we can help debug from there maybe?

**Comment by dfreilich** [comment]
Closing this for now; I assume by now this was resolved. If not, feel free to post a builder.toml and we'll be happy to help!

**Comment by jenspinney** [comment]
We were struggling with this as well, and the example builder linked above doesn't resolve anymore. For others trying the same, take look at this sample builder:

https://github.com/cloudfoundry/stacks/blob/83f9fe8daace7f0806f76bcfb288afd51eedcf6a/fixtures/base_builder.toml

And we referenced the docs here on how to use that builder.toml file to create a builder using the `pack` CLI: https://buildpacks.io/docs/operator-guide/create-a-builder/

**Comment by jenspinney** [comment]
Even after consulting the links mentioned above, we are running into a lot of errors trying to get a custom cloudfoundry cnb-builder working. It would be great to have a README or a script to consult to demonstrate how to generate a builder from the toml files in this repo.

**Comment by drnic** [comment]
Now that Paketo builder is a core part of cf-for-k8s, could we revisit this topic please to allow ppl to make their own builder?

/cc @sclevine @dfreilich

**Comment by cmoulliard** [comment]
I created also my own paketo builder but I got an error during `detect` phase top of a spring boot project.

Here is the scenario: https://gist.github.com/cmoulliard/df61382ad31dbd7ef1550d3133de4e7f
